# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0fa4661b16eca58afcb45b78357c9464376088e427b94b81c599112af051601b4ca6f86ce61dc0875912ead141f3a28d15e4d4d92b508ff1cc9f4ab93e4c7f80

test:
  secret_key_base: 823be9efaf92337055468c84a5216693ac955a5f86212ba4dd0a05c9549ef838357fc53a2c7ddf14f4f2fffd86d2e6d5d706c74094c9e97b7fd02a21383cf7b2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
